model_name : FacebookAI/xlm-roberta-large

batch_size: 16
gradient_accumulation_steps: 1
num_epochs: 10
lr: 1e-5
save_dir: /root/AACS/models/xlm_roberta_large_reviews
train_data_path: /root/AACS/scr/annotation/reviwes/label_train_kept.json
val_data_path: /root/AACS/scr/annotation/reviwes/label_val_kept.json
split:
  train: "train"
  val: "val"

save_strategy : "steps"  
weight_decay: 0.01
seed: 42
warmup_ratio : 0.1
evaluation_strategy: "steps"  
eval_accumulation_steps: 1